### ISSUE TITLE
BEP33

### ISSUE THREAD

**Issue by XJIOP** [nazar-pc/webtorrent-dht#6]
any way to scrape implementation?

**Comment by nazar-pc** [comment]
This project builds on top of [bittorrent-dht](https://github.com/webtorrent/bittorrent-dht) and adds support for working in browser environment. As soon as bittorrent-dht supports BEP33, this project will be updated to support new features.

So you should report this to bittorrent-dht project first and once implementation is landed feel free to ping me if don't rebase project by that time already 😉
